if("undefined"==typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");
+function(c){var f=function(g){c(g).on("click",'[data-dismiss\x3d"alert"]',this.close)};f.VERSION="3.2.0";f.prototype.close=function(g){function h(){a.detach().trigger("closed.bs.alert").remove()}var d=c(this),f=d.attr("data-target");f||(f=d.attr("href"),f=f&&f.replace(/.*(?=#[^\s]*$)/,""));var a=c(f);g&&g.preventDefault();a.length||(a=d.hasClass("alert")?d:d.parent());a.trigger(g=c.Event("close.bs.alert"));g.isDefaultPrevented()||(a.removeClass("in"),c.support.transition&&a.hasClass("fade")?a.one("bsTransitionEnd",
h).emulateTransitionEnd(150):h())};var k=c.fn.alert;c.fn.alert=function(g){return this.each(function(){var h=c(this),d=h.data("bs.alert");d||h.data("bs.alert",d=new f(this));"string"==typeof g&&d[g].call(h)})};c.fn.alert.Constructor=f;c.fn.alert.noConflict=function(){return c.fn.alert=k,this};c(document).on("click.bs.alert.data-api",'[data-dismiss\x3d"alert"]',f.prototype.close)}(jQuery);
+function(c){function f(a){a&&3===a.which||(c(g).remove(),c(h).each(function(){var b=k(c(this)),e={relatedTarget:this};b.hasClass("open")&&(b.trigger(a=c.Event("hide.bs.dropdown",e)),a.isDefaultPrevented()||b.removeClass("open").trigger("hidden.bs.dropdown",e))}))}function k(a){var b=a.attr("data-target");b||(b=a.attr("href"),b=b&&/#[A-Za-z]/.test(b)&&b.replace(/.*(?=#[^\s]*$)/,""));return(b=b&&c(b))&&b.length?b:a.parent()}var g=".dropdown-backdrop",h='[data-toggle\x3d"dropdown"]',d=function(a){c(a).on("click.bs.dropdown",
this.toggle)};d.VERSION="3.2.0";d.prototype.toggle=function(a){var b=c(this);if(!b.is(".disabled, :disabled")){var e=k(b),d=e.hasClass("open");if(f(),!d){"ontouchstart"in document.documentElement&&!e.closest(".navbar-nav").length&&c('\x3cdiv class\x3d"dropdown-backdrop"/\x3e').insertAfter(c(this)).on("click",f);d={relatedTarget:this};if(e.trigger(a=c.Event("show.bs.dropdown",d)),a.isDefaultPrevented())return;b.trigger("focus");e.toggleClass("open").trigger("shown.bs.dropdown",d)}return!1}};d.prototype.keydown=
function(a){if(/(38|40|27)/.test(a.keyCode)){var b=c(this);if(a.preventDefault(),a.stopPropagation(),!b.is(".disabled, :disabled")){var e=k(b),d=e.hasClass("open");if(!d||d&&27==a.keyCode)return 27==a.which&&e.find(h).trigger("focus"),b.trigger("click");b=e.find('[role\x3d"menu"] li:not(.divider):visible a, [role\x3d"listbox"] li:not(.divider):visible a');b.length&&(e=b.index(b.filter(":focus")),38==a.keyCode&&0<e&&e--,40==a.keyCode&&e<b.length-1&&e++,~e||(e=0),b.eq(e).trigger("focus"))}}};var l=
c.fn.dropdown;c.fn.dropdown=function(a){return this.each(function(){var b=c(this),e=b.data("bs.dropdown");e||b.data("bs.dropdown",e=new d(this));"string"==typeof a&&e[a].call(b)})};c.fn.dropdown.Constructor=d;c.fn.dropdown.noConflict=function(){return c.fn.dropdown=l,this};c(document).on("click.bs.dropdown.data-api",f).on("click.bs.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.bs.dropdown.data-api",h,d.prototype.toggle).on("keydown.bs.dropdown.data-api",h+', [role\x3d"menu"], [role\x3d"listbox"]',
d.prototype.keydown)}(jQuery);
$(document).ready(function(){function b(){$(".product, .product-tile, .product-tile-bigger").each(function(){!$(this).hasClass("product-tile-bigger")&&!$(this).hasClass("product-tile")&&($(this).find(".small-slider-content \x3e a:first-child").hover(function(){var a=this;setTimeout(function(){hideWishList($(a).parent().parent());$(a).parent().parent().addClass("tooltip-active")},500)},function(){$(this).parent().parent().removeClass("tooltip-active")}),$(this).hover(function(){detectSlidePos(this)},
function(){hideWishList(this)}))})}function d(a){var c=$(a).hasClass("slider-4")?4:5,b=$(a).hasClass("slider-4")?11:10,f=$(a).hasClass("slider-4")?185:184,c=$(a).hasClass("slider-3")?3:c,b=$(a).hasClass("slider-3")?11:b,f=$(a).hasClass("slider-3")?185:f,d=$(a).find(".bxslider").children().length,e=d<c?!1:!0;$(a).hasClass("no-loop")&&(e=!1);$(a).find(".bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:1,maxSlides:c,responsive:!1,hideControlOnEnd:!0,useCSS:!1,slideWidth:f,slideMargin:b,infiniteLoop:e,
moveSlides:c,onSlideBefore:function(a){a=$(a).parents(".bxslider");$(a).find(".product").off("hover");$(a).find(".product").hover(function(){detectSlidePos(this)},function(){hideWishList(this)})},onSliderLoad:function(a){$(".product-slider .slide-wrapper").css("visibility","visible")}});d<c&&$(a).find(".bx-wrapper").css("max-width",f*c+b*(c-1)+"px");$(a).find(".bx-controls-direction a").click(function(){var a=this;$(a).parents(".bx-wrapper").css("overflow","hidden");setTimeout(function(){$(a).parents(".bx-wrapper").css("overflow",
"visible")},500)})}function g(a){$(a).bxSlider({controls:!0,pager:!1,auto:!1,maxSlides:1,responsive:!1,slideWidth:535,infiniteLoop:!0});$(a).closest(".event-slider").find("img[data-src]").unveil()}var e=null,h="";$("#main-navigation .navbar-nav .sub-menu").mouseenter(function(){e&&clearTimeout(e);$(".sub-menu .dropdown-menu").hide();h=$(this).attr("class");arr=h.split(" ");e=setTimeout(function(){$("."+arr[1]+" .dropdown-menu").show()},300)}).mouseleave(function(){e&&clearTimeout(e);$(".sub-menu .dropdown-menu").hide()});
var k=$("#main-header").height();k>parseInt($("#main-wrapper").css("margin-top"))&&$("body").css("padding-top",k+"px");$("[data-placefocus]").each(function(){var a=$(this).attr("data-placefocus");$(this).val(a);$(this).css("color","#999");$(this).focus(function(){$(this).val()==a&&($(this).val(""),$(this).css("color",""))});$(this).blur(function(){""==$(this).val()&&($(this).val(a),$(this).css("color","#999"))})});$("[data-change-val]").each(function(){var a=$(this).attr("data-change-val"),c=$(this);
$(this).parent().find("li").find("a").click(function(b){b.preventDefault();b=changeDropValue(this);$("#"+a).val(b);$(this).attr("data-class")&&(c[0].className="btn btn-default dropdown-toggle "+$(this).attr("data-class"))})});$("textarea[data-count]").keyup(function(){$(this).parent().find(".char-count").find("b").html($(this).attr("data-count")-$(this).val().length)});$(".big-slider").each(function(){if(1<$(this).find(".bxslider").find("li").length){var a=$(this).find(".bxslider").bxSlider({mode:"fade",
controls:!0,pager:!0,auto:!0,maxSlides:1,responsive:!1,infiniteLoop:!0,onSlideBefore:function(c,b,d){c=$(c).parents(".big-slider").find(".pager-custom").find("a");c.removeClass("active");c.eq(d).addClass("active");a.stopAuto();a.startAuto()}});$(this).find(".pager-custom").find("a").click(function(){var c=$(this).index();a.goToSlide(c);a.stopAuto();a.startAuto()})}else $(this).addClass("only1")});$(this).find(".pager-custom").find("a").click(function(){var a=$(this).index();slider.goToSlide(a)});
$("#carrinho-list .item .qntd a").click(function(){setTimeout(function(){$("#carrinho").parent().addClass("open")});$(this).parents(".item").slideUp("medium",function(){$(this).remove();$("#valor-total b").fadeOut("medium",function(){$("#valor-total b").fadeIn()});$("#carrinho-produtos .item:first-child")[0]||($("#valor-total, #ver-carrinho").hide(),$("#carrinho-produtos").html('\x3cdiv class\x3d"msg" style\x3d"display:none"\x3eCarrinho vazio.\x3c/div\x3e'),$("#carrinho-produtos .msg").fadeIn())})});
$(".drop-section").css("overflow","visible");$(".product-slider .slide-wrapper").css("visibility","hidden");b();$(".product-slider .dropdown-menu li a").click(function(a){a.preventDefault();var c=getSlideWrapper(this);changeDropValue(this);c.fadeOut();a=$(this).attr("href");var e=$(this).closest(".product-slider");$.ajax(a).always(function(){c.fadeIn()}).done(function(a){c.html(a);d(e);b();c.find("img[data-src]").unveil()})});$(".product-slider, .teacher-slider").each(function(){d(this)});$(".product-vertical-slider").each(function(){$(this).find(".slides").bxSlider({controls:!0,
pager:!0,auto:!1,minSlides:1,maxSlides:1,responsive:!1,slideWidth:180,slideMargin:0,infiniteLoop:!0,speed:300,adaptiveHeight:!0,mode:"fade",pagerType:"short",nextSelector:$(this).find(".controls"),pagerSelector:$(this).find(".pages"),prevSelector:$(this).find(".controls")})});$(".fiveslider").each(function(){$(this).find(".bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:5,maxSlides:5,responsive:!1,slideWidth:186,slideMargin:10})});$(".fourslider").each(function(){$(this).find(".bxslider").bxSlider({controls:!0,
pager:!1,auto:!1,minSlides:4,maxSlides:4,responsive:!1,slideWidth:184,slideMargin:10})});g($("#slides-events .bxslider"));$(".event-slider .dropdown-menu li a").click(function(a){a.preventDefault();var c=$(this).closest(".event-slider").find(".store-events-container");changeDropValue(this);c.hide();a=$(this).attr("href");c.load(a,function(a,b,d){c.fadeIn();"success"==b&&g($("#slides-events .bxslider"))})});$("#artigos .bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:1,maxSlides:5,responsive:!1,
slideWidth:184,slideMargin:10});$("#articles .bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:2,maxSlides:2,responsive:!1,slideWidth:474,slideMargin:12});$("#marcas .bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:4,maxSlides:4,responsive:!1,slideWidth:232,slideMargin:10});$("#related-media .bxslider").bxSlider({controls:!0,pager:!1,auto:!1,minSlides:5,maxSlides:5,responsive:!1,useCSS:!1,slideWidth:184,slideMargin:10,infiniteLoop:!0});$("#back-top").fadeOut();$("#back-top a").click(function(){backTop();
return!1});$(window).scroll(function(){150<$(this).scrollTop()?($("#back-top").fadeIn(),$("#top-navigation").slideUp("fast")):($("#back-top").fadeOut(),$("#top-navigation").slideDown("fast",function(){$("#top-navigation").css("overflow","visible")}));if(0<$("footer #logos").length){var a=$("#main-header").height(),b=$("#logos").offset().top-100;$(this).scrollTop()>b?$("#main-header").css("marginTop","-"+a+"px"):$("#main-header").css("marginTop","0")}});$(window).load(function(){$(".big-slider .bx-controls").show()});
$(".aSpinEdit")[0]&&"function"==typeof spinedit&&($(".aSpinEdit").spinedit({minimum:1,maximum:99,step:1}),$(".aSpinEdit").attr("readonly",!0));$("[data-only-numbers], .cep input, .cep-field input").keydown(function(a){a=a.charCode||a.keyCode||0;return 8==a||9==a||13==a||46==a||110==a||190==a||35<=a&&40>=a||48<=a&&57>=a||96<=a&&105>=a});$(".cep-field input:first-child, .cep input:first-child").keyup(function(){5==$(this).val().length&&$(this).parent().find("input").eq(1)[0].focus()})});
function pop(b,d,g,e){window.open(e,g,"height\x3d"+d+",width\x3d"+b+",top\x3d"+(screen.height?(screen.height-d)/2:0)+",left\x3d"+(screen.width?(screen.width-b)/2:0)+",scrollbars\x3dno,toolbar\x3d0,resizable\x3d0,status\x3d0")}function backTop(){$("body,html").animate({scrollTop:0},800)}function detectSlidePos(b){var d=$("#main-header").width()/2;$(b).offset().left>d?$(b).addClass("right"):$(b).removeClass("right")}function hideWishList(b){$(b).find(".open").removeClass("open")}
function changeDropValue(b){$(b).parents("ul").parent().find("[data-toggle]").eq(0).html($(b).text()+' \x3cb class\x3d"caret"\x3e\x3c/b\x3e');return $(b).attr("href").replace("#","")}function getSlideWrapper(b){return $(b).parent().parent().parent().parent().parent().find(".slide-wrapper")};
$(document).ready(function(){$("#categories .category h2").click(function(){$(this).parent().find(".cat-links").eq(0).slideToggle("fast",function(){$(this).parent().toggleClass("closed")})})});function refreshSortBar(a){var b=a.clone();a.is(":first-child")?($("#results .sort:last-child").remove(),$("#results").append(b)):($("#results .sort:first-child").remove(),$("#results").prepend(b))};
MiniCartUtils={loadShippincartPage:function(){$("#custom-container-shippingcart").length&&(loading(),window.setTimeout("location.reload()",0))},formAjaxSubmit:function(a){if(a)return $.ajax({url:a.attr("action"),data:a.serialize(),type:"POST"}).done(function(a){0<a.length&&($("#menu-cart-badge").fadeOut().html(a).fadeIn(),MiniCartUtils.loadShippincartPage(),MiniCartUtils.loadMiniCartFuncions())}),!1},startingLoading:function(){loadingContext=context+"/assets/images/custom/ajax-loader-small.gif";containerClass=
"dropdown-menu custom-dropdown-menu custom-mini-cart-loading";containerId="carrinho-list";html='\x3cdiv class\x3d"'+containerClass+'" id\x3d"'+containerId+'"\x3e\x3cimg src\x3d"'+loadingContext+'"/\x3e\x3cdiv class\x3d"text"\x3e'+mini_shopping_cart_loading+"\x3c/div\x3e\x3c/div\x3e";$("#mini-cart-el").html(html)},loadMiniCartFuncions:function(){$("[data-remove-cart]").click(function(a){form=$(this).closest("form");MiniCartUtils.startingLoading();MiniCartUtils.formAjaxSubmit(form)});$("[data-add-item-cart]").click(function(a){form=
$(this).closest("form");element=form.find(".item-quantity");99>element.val()&&(_result=Number(element.val())+Number(1),element.attr("value",_result),MiniCartUtils.startingLoading(),MiniCartUtils.formAjaxSubmit(form));return!1});$("[data-remove-item-cart]").click(function(a){form=$(this).closest("form");element=form.find(".item-quantity");1<element.val()&&(_result=Number(element.val())-Number(1),element.attr("value",_result),MiniCartUtils.startingLoading(),MiniCartUtils.formAjaxSubmit(form));return!1});
$("[data-submit-checkout]").click(function(a){form=$(this).closest("form");form.submit()})}};$(document).ready(function(){MiniCartUtils.loadMiniCartFuncions();loadMiniShoppingCart()});function loadMiniShoppingCart(){isSecureConnection()&&(miniCartURL=context+"/secure/ajax/mini_cart/menu_cart.jsp",$.ajax({url:miniCartURL,type:"GET",cache:!1,success:function(a,b,c){0<a.length&&($("#menu-cart-badge").html(a),MiniCartUtils.loadMiniCartFuncions())}}))};
(function(s,H,f,w){var K=f("html"),p=f(s),q=f(H),b=f.fancybox=function(){b.open.apply(this,arguments)},J=navigator.userAgent.match(/msie/i),C=null,t=H.createTouch!==w,u=function(a){return a&&a.hasOwnProperty&&a instanceof f},r=function(a){return a&&"string"===f.type(a)},F=function(a){return r(a)&&0<a.indexOf("%")},m=function(a,d){var e=parseInt(a,10)||0;d&&F(a)&&(e*=b.getViewport()[d]/100);return Math.ceil(e)},x=function(a,b){return m(a,b)+"px"};f.extend(b,{version:"2.1.5",defaults:{padding:15,margin:20,
width:800,height:600,minWidth:100,minHeight:100,maxWidth:9999,maxHeight:9999,pixelRatio:1,autoSize:!0,autoHeight:!1,autoWidth:!1,autoResize:!0,autoCenter:!t,fitToView:!0,aspectRatio:!1,topRatio:0.5,leftRatio:0.5,scrolling:"auto",wrapCSS:"",arrows:!0,closeBtn:!0,closeClick:!1,nextClick:!1,mouseWheel:!0,autoPlay:!1,playSpeed:3E3,preload:3,modal:!1,loop:!0,ajax:{dataType:"html",headers:{"X-fancyBox":!0}},iframe:{scrolling:"auto",preload:!0},swf:{wmode:"transparent",allowfullscreen:"true",allowscriptaccess:"always"},
keys:{next:{13:"left",34:"up",39:"left",40:"up"},prev:{8:"right",33:"down",37:"right",38:"down"},close:[27],play:[32],toggle:[70]},direction:{next:"left",prev:"right"},scrollOutside:!0,index:0,type:null,href:null,content:null,title:null,tpl:{wrap:'\x3cdiv class\x3d"fancybox-wrap" tabIndex\x3d"-1"\x3e\x3cdiv class\x3d"fancybox-skin"\x3e\x3cdiv class\x3d"fancybox-outer"\x3e\x3cdiv class\x3d"fancybox-inner"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',image:'\x3cimg class\x3d"fancybox-image" src\x3d"{href}" alt\x3d"" /\x3e',
iframe:'\x3ciframe id\x3d"fancybox-frame{rnd}" name\x3d"fancybox-frame{rnd}" class\x3d"fancybox-iframe" frameborder\x3d"0" vspace\x3d"0" hspace\x3d"0" webkitAllowFullScreen mozallowfullscreen allowFullScreen'+(J?' allowtransparency\x3d"true"':"")+"\x3e\x3c/iframe\x3e",error:'\x3cp class\x3d"fancybox-error"\x3eThe requested content cannot be loaded.\x3cbr/\x3ePlease try again later.\x3c/p\x3e',closeBtn:'\x3ca title\x3d"Close" class\x3d"fancybox-item fancybox-close" href\x3d"javascript:;"\x3e\x3c/a\x3e',
next:'\x3ca title\x3d"Next" class\x3d"fancybox-nav fancybox-next" href\x3d"javascript:;"\x3e\x3cspan\x3e\x3c/span\x3e\x3c/a\x3e',prev:'\x3ca title\x3d"Previous" class\x3d"fancybox-nav fancybox-prev" href\x3d"javascript:;"\x3e\x3cspan\x3e\x3c/span\x3e\x3c/a\x3e'},openEffect:"fade",openSpeed:250,openEasing:"swing",openOpacity:!0,openMethod:"zoomIn",closeEffect:"fade",closeSpeed:250,closeEasing:"swing",closeOpacity:!0,closeMethod:"zoomOut",nextEffect:"elastic",nextSpeed:250,nextEasing:"swing",nextMethod:"changeIn",
prevEffect:"elastic",prevSpeed:250,prevEasing:"swing",prevMethod:"changeOut",helpers:{overlay:!0,title:!0},onCancel:f.noop,beforeLoad:f.noop,afterLoad:f.noop,beforeShow:f.noop,afterShow:f.noop,beforeChange:f.noop,beforeClose:f.noop,afterClose:f.noop},group:{},opts:{},previous:null,coming:null,current:null,isActive:!1,isOpen:!1,isOpened:!1,wrap:null,skin:null,outer:null,inner:null,player:{timer:null,isActive:!1},ajaxLoad:null,imgPreload:null,transitions:{},helpers:{},open:function(a,d){if(a&&(f.isPlainObject(d)||
(d={}),!1!==b.close(!0)))return f.isArray(a)||(a=u(a)?f(a).get():[a]),f.each(a,function(e,c){var l={},g,h,k,n,m;"object"===f.type(c)&&(c.nodeType&&(c=f(c)),u(c)?(l={href:c.data("fancybox-href")||c.attr("href"),title:c.data("fancybox-title")||c.attr("title"),isDom:!0,element:c},f.metadata&&f.extend(!0,l,c.metadata())):l=c);g=d.href||l.href||(r(c)?c:null);h=d.title!==w?d.title:l.title||"";n=(k=d.content||l.content)?"html":d.type||l.type;!n&&l.isDom&&(n=c.data("fancybox-type"),n||(n=(n=c.prop("class").match(/fancybox\.(\w+)/))?
n[1]:null));r(g)&&(n||(b.isImage(g)?n="image":b.isSWF(g)?n="swf":"#"===g.charAt(0)?n="inline":r(c)&&(n="html",k=c)),"ajax"===n&&(m=g.split(/\s+/,2),g=m.shift(),m=m.shift()));k||("inline"===n?g?k=f(r(g)?g.replace(/.*(?=#[^\s]+$)/,""):g):l.isDom&&(k=c):"html"===n?k=g:!n&&!g&&l.isDom&&(n="inline",k=c));f.extend(l,{href:g,type:n,content:k,title:h,selector:m});a[e]=l}),b.opts=f.extend(!0,{},b.defaults,d),d.keys!==w&&(b.opts.keys=d.keys?f.extend({},b.defaults.keys,d.keys):!1),b.group=a,b._start(b.opts.index)},
cancel:function(){var a=b.coming;a&&!1!==b.trigger("onCancel")&&(b.hideLoading(),b.ajaxLoad&&b.ajaxLoad.abort(),b.ajaxLoad=null,b.imgPreload&&(b.imgPreload.onload=b.imgPreload.onerror=null),a.wrap&&a.wrap.stop(!0,!0).trigger("onReset").remove(),b.coming=null,b.current||b._afterZoomOut(a))},close:function(a){b.cancel();!1!==b.trigger("beforeClose")&&(b.unbindEvents(),b.isActive&&(!b.isOpen||!0===a?(f(".fancybox-wrap").stop(!0).trigger("onReset").remove(),b._afterZoomOut()):(b.isOpen=b.isOpened=!1,
b.isClosing=!0,f(".fancybox-item, .fancybox-nav").remove(),b.wrap.stop(!0,!0).removeClass("fancybox-opened"),b.transitions[b.current.closeMethod]())))},play:function(a){var d=function(){clearTimeout(b.player.timer)},e=function(){d();b.current&&b.player.isActive&&(b.player.timer=setTimeout(b.next,b.current.playSpeed))},c=function(){d();q.unbind(".player");b.player.isActive=!1;b.trigger("onPlayEnd")};if(!0===a||!b.player.isActive&&!1!==a){if(b.current&&(b.current.loop||b.current.index<b.group.length-
1))b.player.isActive=!0,q.bind({"onCancel.player beforeClose.player":c,"onUpdate.player":e,"beforeLoad.player":d}),e(),b.trigger("onPlayStart")}else c()},next:function(a){var d=b.current;d&&(r(a)||(a=d.direction.next),b.jumpto(d.index+1,a,"next"))},prev:function(a){var d=b.current;d&&(r(a)||(a=d.direction.prev),b.jumpto(d.index-1,a,"prev"))},jumpto:function(a,d,e){var c=b.current;c&&(a=m(a),b.direction=d||c.direction[a>=c.index?"next":"prev"],b.router=e||"jumpto",c.loop&&(0>a&&(a=c.group.length+a%
c.group.length),a%=c.group.length),c.group[a]!==w&&(b.cancel(),b._start(a)))},reposition:function(a,d){var e=b.current,c=e?e.wrap:null,l;c&&(l=b._getPosition(d),a&&"scroll"===a.type?(delete l.position,c.stop(!0,!0).animate(l,200)):(c.css(l),e.pos=f.extend({},e.dim,l)))},update:function(a){var d=a&&a.type,e=!d||"orientationchange"===d;e&&(clearTimeout(C),C=null);b.isOpen&&!C&&(C=setTimeout(function(){var c=b.current;c&&!b.isClosing&&(b.wrap.removeClass("fancybox-tmp"),(e||"load"===d||"resize"===d&&
c.autoResize)&&b._setDimension(),"scroll"===d&&c.canShrink||b.reposition(a),b.trigger("onUpdate"),C=null)},e&&!t?0:300))},toggle:function(a){b.isOpen&&(b.current.fitToView="boolean"===f.type(a)?a:!b.current.fitToView,t&&(b.wrap.removeAttr("style").addClass("fancybox-tmp"),b.trigger("onUpdate")),b.update())},hideLoading:function(){q.unbind(".loading");f("#fancybox-loading").remove()},showLoading:function(){var a,d;b.hideLoading();a=f('\x3cdiv id\x3d"fancybox-loading"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e').click(b.cancel).appendTo("body");
q.bind("keydown.loading",function(a){if(27===(a.which||a.keyCode))a.preventDefault(),b.cancel()});b.defaults.fixed||(d=b.getViewport(),a.css({position:"absolute",top:0.5*d.h+d.y,left:0.5*d.w+d.x}))},getViewport:function(){var a=b.current&&b.current.locked||!1,d={x:p.scrollLeft(),y:p.scrollTop()};a?(d.w=a[0].clientWidth,d.h=a[0].clientHeight):(d.w=t&&s.innerWidth?s.innerWidth:p.width(),d.h=t&&s.innerHeight?s.innerHeight:p.height());return d},unbindEvents:function(){b.wrap&&u(b.wrap)&&b.wrap.unbind(".fb");
q.unbind(".fb");p.unbind(".fb")},bindEvents:function(){var a=b.current,d;a&&(p.bind("orientationchange.fb"+(t?"":" resize.fb")+(a.autoCenter&&!a.locked?" scroll.fb":""),b.update),(d=a.keys)&&q.bind("keydown.fb",function(e){var c=e.which||e.keyCode,l=e.target||e.srcElement;if(27===c&&b.coming)return!1;!e.ctrlKey&&!e.altKey&&(!e.shiftKey&&!e.metaKey&&(!l||!l.type&&!f(l).is("[contenteditable]")))&&f.each(d,function(d,l){if(1<a.group.length&&l[c]!==w)return b[d](l[c]),e.preventDefault(),!1;if(-1<f.inArray(c,
l))return b[d](),e.preventDefault(),!1})}),f.fn.mousewheel&&a.mouseWheel&&b.wrap.bind("mousewheel.fb",function(d,c,l,g){for(var h=f(d.target||null),k=!1;h.length&&!k&&!h.is(".fancybox-skin")&&!h.is(".fancybox-wrap");)k=h[0]&&!(h[0].style.overflow&&"hidden"===h[0].style.overflow)&&(h[0].clientWidth&&h[0].scrollWidth>h[0].clientWidth||h[0].clientHeight&&h[0].scrollHeight>h[0].clientHeight),h=f(h).parent();if(0!==c&&!k&&1<b.group.length&&!a.canShrink){if(0<g||0<l)b.prev(0<g?"down":"left");else if(0>
g||0>l)b.next(0>g?"up":"right");d.preventDefault()}}))},trigger:function(a,d){var e,c=d||b.coming||b.current;if(c){f.isFunction(c[a])&&(e=c[a].apply(c,Array.prototype.slice.call(arguments,1)));if(!1===e)return!1;c.helpers&&f.each(c.helpers,function(d,e){if(e&&b.helpers[d]&&f.isFunction(b.helpers[d][a]))b.helpers[d][a](f.extend(!0,{},b.helpers[d].defaults,e),c)});q.trigger(a)}},isImage:function(a){return r(a)&&a.match(/(^data:image\/.*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg)((\?|#).*)?$)/i)},isSWF:function(a){return r(a)&&
a.match(/\.(swf)((\?|#).*)?$/i)},_start:function(a){var d={},e,c;a=m(a);e=b.group[a]||null;if(!e)return!1;d=f.extend(!0,{},b.opts,e);e=d.margin;c=d.padding;"number"===f.type(e)&&(d.margin=[e,e,e,e]);"number"===f.type(c)&&(d.padding=[c,c,c,c]);d.modal&&f.extend(!0,d,{closeBtn:!1,closeClick:!1,nextClick:!1,arrows:!1,mouseWheel:!1,keys:null,helpers:{overlay:{closeClick:!1}}});d.autoSize&&(d.autoWidth=d.autoHeight=!0);"auto"===d.width&&(d.autoWidth=!0);"auto"===d.height&&(d.autoHeight=!0);d.group=b.group;
d.index=a;b.coming=d;if(!1===b.trigger("beforeLoad"))b.coming=null;else{c=d.type;e=d.href;if(!c)return b.coming=null,b.current&&b.router&&"jumpto"!==b.router?(b.current.index=a,b[b.router](b.direction)):!1;b.isActive=!0;if("image"===c||"swf"===c)d.autoHeight=d.autoWidth=!1,d.scrolling="visible";"image"===c&&(d.aspectRatio=!0);"iframe"===c&&t&&(d.scrolling="scroll");d.wrap=f(d.tpl.wrap).addClass("fancybox-"+(t?"mobile":"desktop")+" fancybox-type-"+c+" fancybox-tmp "+d.wrapCSS).appendTo(d.parent||"body");
f.extend(d,{skin:f(".fancybox-skin",d.wrap),outer:f(".fancybox-outer",d.wrap),inner:f(".fancybox-inner",d.wrap)});f.each(["Top","Right","Bottom","Left"],function(a,b){d.skin.css("padding"+b,x(d.padding[a]))});b.trigger("onReady");if("inline"===c||"html"===c){if(!d.content||!d.content.length)return b._error("content")}else if(!e)return b._error("href");"image"===c?b._loadImage():"ajax"===c?b._loadAjax():"iframe"===c?b._loadIframe():b._afterLoad()}},_error:function(a){f.extend(b.coming,{type:"html",
autoWidth:!0,autoHeight:!0,minWidth:0,minHeight:0,scrolling:"no",hasError:a,content:b.coming.tpl.error});b._afterLoad()},_loadImage:function(){var a=b.imgPreload=new Image;a.onload=function(){this.onload=this.onerror=null;b.coming.width=this.width/b.opts.pixelRatio;b.coming.height=this.height/b.opts.pixelRatio;b._afterLoad()};a.onerror=function(){this.onload=this.onerror=null;b._error("image")};a.src=b.coming.href;!0!==a.complete&&b.showLoading()},_loadAjax:function(){var a=b.coming;b.showLoading();
b.ajaxLoad=f.ajax(f.extend({},a.ajax,{url:a.href,error:function(a,e){b.coming&&"abort"!==e?b._error("ajax",a):b.hideLoading()},success:function(d,e){"success"===e&&(a.content=d,b._afterLoad())}}))},_loadIframe:function(){var a=b.coming,d=f(a.tpl.iframe.replace(/\{rnd\}/g,(new Date).getTime())).attr("scrolling",t?"auto":a.iframe.scrolling).attr("src",a.href);f(a.wrap).bind("onReset",function(){try{f(this).find("iframe").hide().attr("src","//about:blank").end().empty()}catch(a){}});a.iframe.preload&&
(b.showLoading(),d.one("load",function(){f(this).data("ready",1);t||f(this).bind("load.fb",b.update);f(this).parents(".fancybox-wrap").width("100%").removeClass("fancybox-tmp").show();b._afterLoad()}));a.content=d.appendTo(a.inner);a.iframe.preload||b._afterLoad()},_preloadImages:function(){var a=b.group,d=b.current,e=a.length,c=d.preload?Math.min(d.preload,e-1):0,f,g;for(g=1;g<=c;g+=1)f=a[(d.index+g)%e],"image"===f.type&&f.href&&((new Image).src=f.href)},_afterLoad:function(){var a=b.coming,d=b.current,
e,c,l,g,h;b.hideLoading();if(a&&!1!==b.isActive)if(!1===b.trigger("afterLoad",a,d))a.wrap.stop(!0).trigger("onReset").remove(),b.coming=null;else{d&&(b.trigger("beforeChange",d),d.wrap.stop(!0).removeClass("fancybox-opened").find(".fancybox-item, .fancybox-nav").remove());b.unbindEvents();e=a.content;c=a.type;l=a.scrolling;f.extend(b,{wrap:a.wrap,skin:a.skin,outer:a.outer,inner:a.inner,current:a,previous:d});g=a.href;switch(c){case "inline":case "ajax":case "html":a.selector?e=f("\x3cdiv\x3e").html(e).find(a.selector):
u(e)&&(e.data("fancybox-placeholder")||e.data("fancybox-placeholder",f('\x3cdiv class\x3d"fancybox-placeholder"\x3e\x3c/div\x3e').insertAfter(e).hide()),e=e.show().detach(),a.wrap.bind("onReset",function(){f(this).find(e).length&&e.hide().replaceAll(e.data("fancybox-placeholder")).data("fancybox-placeholder",!1)}));break;case "image":e=a.tpl.image.replace("{href}",g);break;case "swf":e='\x3cobject id\x3d"fancybox-swf" classid\x3d"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width\x3d"100%" height\x3d"100%"\x3e\x3cparam name\x3d"movie" value\x3d"'+
g+'"\x3e\x3c/param\x3e',h="",f.each(a.swf,function(a,b){e+='\x3cparam name\x3d"'+a+'" value\x3d"'+b+'"\x3e\x3c/param\x3e';h+=" "+a+'\x3d"'+b+'"'}),e+='\x3cembed src\x3d"'+g+'" type\x3d"application/x-shockwave-flash" width\x3d"100%" height\x3d"100%"'+h+"\x3e\x3c/embed\x3e\x3c/object\x3e"}(!u(e)||!e.parent().is(a.inner))&&a.inner.append(e);b.trigger("beforeShow");a.inner.css("overflow","yes"===l?"scroll":"no"===l?"hidden":l);b._setDimension();b.reposition();b.isOpen=!1;b.coming=null;b.bindEvents();
if(b.isOpened){if(d.prevMethod)b.transitions[d.prevMethod]()}else f(".fancybox-wrap").not(a.wrap).stop(!0).trigger("onReset").remove();b.transitions[b.isOpened?a.nextMethod:a.openMethod]();b._preloadImages()}},_setDimension:function(){var a=b.getViewport(),d=0,e=!1,c=!1,e=b.wrap,l=b.skin,g=b.inner,h=b.current,c=h.width,k=h.height,n=h.minWidth,v=h.minHeight,p=h.maxWidth,q=h.maxHeight,t=h.scrolling,r=h.scrollOutside?h.scrollbarWidth:0,y=h.margin,z=m(y[1]+y[3]),s=m(y[0]+y[2]),w,A,u,D,B,G,C,E,I;e.add(l).add(g).width("auto").height("auto").removeClass("fancybox-tmp");
y=m(l.outerWidth(!0)-l.width());w=m(l.outerHeight(!0)-l.height());A=z+y;u=s+w;D=F(c)?(a.w-A)*m(c)/100:c;B=F(k)?(a.h-u)*m(k)/100:k;if("iframe"===h.type){if(I=h.content,h.autoHeight&&1===I.data("ready"))try{I[0].contentWindow.document.location&&(g.width(D).height(9999),G=I.contents().find("body"),r&&G.css("overflow-x","hidden"),B=G.outerHeight(!0))}catch(H){}}else if(h.autoWidth||h.autoHeight)g.addClass("fancybox-tmp"),h.autoWidth||g.width(D),h.autoHeight||g.height(B),h.autoWidth&&(D=g.width()),h.autoHeight&&
(B=g.height()),g.removeClass("fancybox-tmp");c=m(D);k=m(B);E=D/B;n=m(F(n)?m(n,"w")-A:n);p=m(F(p)?m(p,"w")-A:p);v=m(F(v)?m(v,"h")-u:v);q=m(F(q)?m(q,"h")-u:q);G=p;C=q;h.fitToView&&(p=Math.min(a.w-A,p),q=Math.min(a.h-u,q));A=a.w-z;s=a.h-s;h.aspectRatio?(c>p&&(c=p,k=m(c/E)),k>q&&(k=q,c=m(k*E)),c<n&&(c=n,k=m(c/E)),k<v&&(k=v,c=m(k*E))):(c=Math.max(n,Math.min(c,p)),h.autoHeight&&"iframe"!==h.type&&(g.width(c),k=g.height()),k=Math.max(v,Math.min(k,q)));if(h.fitToView)if(g.width(c).height(k),e.width(c+y),
a=e.width(),z=e.height(),h.aspectRatio)for(;(a>A||z>s)&&c>n&&k>v&&!(19<d++);)k=Math.max(v,Math.min(q,k-10)),c=m(k*E),c<n&&(c=n,k=m(c/E)),c>p&&(c=p,k=m(c/E)),g.width(c).height(k),e.width(c+y),a=e.width(),z=e.height();else c=Math.max(n,Math.min(c,c-(a-A))),k=Math.max(v,Math.min(k,k-(z-s)));r&&"auto"===t&&(k<B&&c+y+r<A)&&(c+=r);g.width(c).height(k);e.width(c+y);a=e.width();z=e.height();e=(a>A||z>s)&&c>n&&k>v;c=h.aspectRatio?c<G&&k<C&&c<D&&k<B:(c<G||k<C)&&(c<D||k<B);f.extend(h,{dim:{width:x(a),height:x(z)},
origWidth:D,origHeight:B,canShrink:e,canExpand:c,wPadding:y,hPadding:w,wrapSpace:z-l.outerHeight(!0),skinSpace:l.height()-k});!I&&h.autoHeight&&(k>v&&k<q&&!c)&&g.height("auto")},_getPosition:function(a){var d=b.current,e=b.getViewport(),c=d.margin,f=b.wrap.width()+c[1]+c[3],g=b.wrap.height()+c[0]+c[2],c={position:"absolute",top:c[0],left:c[3]};d.autoCenter&&d.fixed&&!a&&g<=e.h&&f<=e.w?c.position="fixed":d.locked||(c.top+=e.y,c.left+=e.x);c.top=x(Math.max(c.top,c.top+(e.h-g)*d.topRatio));c.left=x(Math.max(c.left,
c.left+(e.w-f)*d.leftRatio));return c},_afterZoomIn:function(){var a=b.current;a&&(b.isOpen=b.isOpened=!0,b.wrap.css("overflow","visible").addClass("fancybox-opened"),b.update(),(a.closeClick||a.nextClick&&1<b.group.length)&&b.inner.css("cursor","pointer").bind("click.fb",function(d){!f(d.target).is("a")&&!f(d.target).parent().is("a")&&(d.preventDefault(),b[a.closeClick?"close":"next"]())}),a.closeBtn&&f(a.tpl.closeBtn).appendTo(b.skin).bind("click.fb",function(a){a.preventDefault();b.close()}),a.arrows&&
1<b.group.length&&((a.loop||0<a.index)&&f(a.tpl.prev).appendTo(b.outer).bind("click.fb",b.prev),(a.loop||a.index<b.group.length-1)&&f(a.tpl.next).appendTo(b.outer).bind("click.fb",b.next)),b.trigger("afterShow"),!a.loop&&a.index===a.group.length-1?b.play(!1):b.opts.autoPlay&&!b.player.isActive&&(b.opts.autoPlay=!1,b.play()))},_afterZoomOut:function(a){a=a||b.current;f(".fancybox-wrap").trigger("onReset").remove();f.extend(b,{group:{},opts:{},router:!1,current:null,isActive:!1,isOpened:!1,isOpen:!1,
isClosing:!1,wrap:null,skin:null,outer:null,inner:null});b.trigger("afterClose",a)}});b.transitions={getOrigPosition:function(){var a=b.current,d=a.element,e=a.orig,c={},f=50,g=50,h=a.hPadding,k=a.wPadding,n=b.getViewport();!e&&a.isDom&&d.is(":visible")&&(e=d.find("img:first"),e.length||(e=d));u(e)?(c=e.offset(),e.is("img")&&(f=e.outerWidth(),g=e.outerHeight())):(c.top=n.y+(n.h-g)*a.topRatio,c.left=n.x+(n.w-f)*a.leftRatio);if("fixed"===b.wrap.css("position")||a.locked)c.top-=n.y,c.left-=n.x;return{top:x(c.top-
h*a.topRatio),left:x(c.left-k*a.leftRatio),width:x(f+k),height:x(g+h)}},step:function(a,d){var e,c,f=d.prop;c=b.current;var g=c.wrapSpace,h=c.skinSpace;if("width"===f||"height"===f)e=d.end===d.start?1:(a-d.start)/(d.end-d.start),b.isClosing&&(e=1-e),c="width"===f?c.wPadding:c.hPadding,c=a-c,b.skin[f](m("width"===f?c:c-g*e)),b.inner[f](m("width"===f?c:c-g*e-h*e))},zoomIn:function(){var a=b.current,d=a.pos,e=a.openEffect,c="elastic"===e,l=f.extend({opacity:1},d);delete l.position;c?(d=this.getOrigPosition(),
a.openOpacity&&(d.opacity=0.1)):"fade"===e&&(d.opacity=0.1);b.wrap.css(d).animate(l,{duration:"none"===e?0:a.openSpeed,easing:a.openEasing,step:c?this.step:null,complete:b._afterZoomIn})},zoomOut:function(){var a=b.current,d=a.closeEffect,e="elastic"===d,c={opacity:0.1};e&&(c=this.getOrigPosition(),a.closeOpacity&&(c.opacity=0.1));b.wrap.animate(c,{duration:"none"===d?0:a.closeSpeed,easing:a.closeEasing,step:e?this.step:null,complete:b._afterZoomOut})},changeIn:function(){var a=b.current,d=a.nextEffect,
e=a.pos,c={opacity:1},f=b.direction,g;e.opacity=0.1;"elastic"===d&&(g="down"===f||"up"===f?"top":"left","down"===f||"right"===f?(e[g]=x(m(e[g])-200),c[g]="+\x3d200px"):(e[g]=x(m(e[g])+200),c[g]="-\x3d200px"));"none"===d?b._afterZoomIn():b.wrap.css(e).animate(c,{duration:a.nextSpeed,easing:a.nextEasing,complete:b._afterZoomIn})},changeOut:function(){var a=b.previous,d=a.prevEffect,e={opacity:0.1},c=b.direction;"elastic"===d&&(e["down"===c||"up"===c?"top":"left"]=("up"===c||"left"===c?"-":"+")+"\x3d200px");
a.wrap.animate(e,{duration:"none"===d?0:a.prevSpeed,easing:a.prevEasing,complete:function(){f(this).trigger("onReset").remove()}})}};b.helpers.overlay={defaults:{closeClick:!0,speedOut:200,showEarly:!0,css:{},locked:!t,fixed:!0},overlay:null,fixed:!1,el:f("html"),create:function(a){a=f.extend({},this.defaults,a);this.overlay&&this.close();this.overlay=f('\x3cdiv class\x3d"fancybox-overlay"\x3e\x3c/div\x3e').appendTo(b.coming?b.coming.parent:a.parent);this.fixed=!1;a.fixed&&b.defaults.fixed&&(this.overlay.addClass("fancybox-overlay-fixed"),
this.fixed=!0)},open:function(a){var d=this;a=f.extend({},this.defaults,a);this.overlay?this.overlay.unbind(".overlay").width("auto").height("auto"):this.create(a);this.fixed||(p.bind("resize.overlay",f.proxy(this.update,this)),this.update());a.closeClick&&this.overlay.bind("click.overlay",function(a){if(f(a.target).hasClass("fancybox-overlay"))return b.isActive?b.close():d.close(),!1});this.overlay.css(a.css).show()},close:function(){var a,b;p.unbind("resize.overlay");this.el.hasClass("fancybox-lock")&&
(f(".fancybox-margin").removeClass("fancybox-margin"),a=p.scrollTop(),b=p.scrollLeft(),this.el.removeClass("fancybox-lock"),p.scrollTop(a).scrollLeft(b));f(".fancybox-overlay").remove().hide();f.extend(this,{overlay:null,fixed:!1})},update:function(){var a="100%",b;this.overlay.width(a).height("100%");J?(b=Math.max(H.documentElement.offsetWidth,H.body.offsetWidth),q.width()>b&&(a=q.width())):q.width()>p.width()&&(a=q.width());this.overlay.width(a).height(q.height())},onReady:function(a,b){var e=this.overlay;
f(".fancybox-overlay").stop(!0,!0);e||this.create(a);a.locked&&this.fixed&&b.fixed&&(e||(this.margin=q.height()>p.height()?f("html").css("margin-right").replace("px",""):!1),b.locked=this.overlay.append(b.wrap),b.fixed=!1);!0===a.showEarly&&this.beforeShow.apply(this,arguments)},beforeShow:function(a,b){var e,c;b.locked&&(!1!==this.margin&&(f("*").filter(function(){return"fixed"===f(this).css("position")&&!f(this).hasClass("fancybox-overlay")&&!f(this).hasClass("fancybox-wrap")}).addClass("fancybox-margin"),
this.el.addClass("fancybox-margin")),e=p.scrollTop(),c=p.scrollLeft(),this.el.addClass("fancybox-lock"),p.scrollTop(e).scrollLeft(c));this.open(a)},onUpdate:function(){this.fixed||this.update()},afterClose:function(a){this.overlay&&!b.coming&&this.overlay.fadeOut(a.speedOut,f.proxy(this.close,this))}};b.helpers.title={defaults:{type:"float",position:"bottom"},beforeShow:function(a){var d=b.current,e=d.title,c=a.type;f.isFunction(e)&&(e=e.call(d.element,d));if(r(e)&&""!==f.trim(e)){d=f('\x3cdiv class\x3d"fancybox-title fancybox-title-'+
c+'-wrap"\x3e'+e+"\x3c/div\x3e");switch(c){case "inside":c=b.skin;break;case "outside":c=b.wrap;break;case "over":c=b.inner;break;default:c=b.skin,d.appendTo("body"),J&&d.width(d.width()),d.wrapInner('\x3cspan class\x3d"child"\x3e\x3c/span\x3e'),b.current.margin[2]+=Math.abs(m(d.css("margin-bottom")))}d["top"===a.position?"prependTo":"appendTo"](c)}}};f.fn.fancybox=function(a){var d,e=f(this),c=this.selector||"",l=function(g){var h=f(this).blur(),k=d,l,m;!g.ctrlKey&&!g.altKey&&!g.shiftKey&&!g.metaKey&&
!h.is(".fancybox-wrap")&&(l=a.groupAttr||"data-fancybox-group",m=h.attr(l),m||(l="rel",m=h.get(0)[l]),m&&""!==m&&"nofollow"!==m&&(h=c.length?f(c):e,h=h.filter("["+l+'\x3d"'+m+'"]'),k=h.index(this)),a.index=k,!1!==b.open(h,a)&&g.preventDefault())};a=a||{};d=a.index||0;!c||!1===a.live?e.unbind("click.fb-start").bind("click.fb-start",l):q.undelegate(c,"click.fb-start").delegate(c+":not('.fancybox-item, .fancybox-nav')","click.fb-start",l);this.filter("[data-fancybox-start\x3d1]").trigger("click");return this};
q.ready(function(){var a,d;f.scrollbarWidth===w&&(f.scrollbarWidth=function(){var a=f('\x3cdiv style\x3d"width:50px;height:50px;overflow:auto"\x3e\x3cdiv/\x3e\x3c/div\x3e').appendTo("body"),b=a.children(),b=b.innerWidth()-b.height(99).innerWidth();a.remove();return b});if(f.support.fixedPosition===w){a=f.support;d=f('\x3cdiv style\x3d"position:fixed;top:20px;"\x3e\x3c/div\x3e').appendTo("body");var e=20===d[0].offsetTop||15===d[0].offsetTop;d.remove();a.fixedPosition=e}f.extend(b.defaults,{scrollbarWidth:f.scrollbarWidth(),
fixed:f.support.fixedPosition,parent:f("body")});a=f(s).width();K.addClass("fancybox-lock-test");d=f(s).width();K.removeClass("fancybox-lock-test");f("\x3cstyle type\x3d'text/css'\x3e.fancybox-margin{margin-right:"+(d-a)+"px;}\x3c/style\x3e").appendTo("head")})})(window,document,jQuery);
(function(e){var d=e.fancybox;d.helpers.buttons={defaults:{skipSingle:!1,position:"top",tpl:'\x3cdiv id\x3d"fancybox-buttons"\x3e\x3cul\x3e\x3cli\x3e\x3ca class\x3d"btnPrev" title\x3d"Previous" href\x3d"javascript:;"\x3e\x3c/a\x3e\x3c/li\x3e\x3cli\x3e\x3ca class\x3d"btnPlay" title\x3d"Start slideshow" href\x3d"javascript:;"\x3e\x3c/a\x3e\x3c/li\x3e\x3cli\x3e\x3ca class\x3d"btnNext" title\x3d"Next" href\x3d"javascript:;"\x3e\x3c/a\x3e\x3c/li\x3e\x3cli\x3e\x3ca class\x3d"btnToggle" title\x3d"Toggle size" href\x3d"javascript:;"\x3e\x3c/a\x3e\x3c/li\x3e\x3cli\x3e\x3ca class\x3d"btnClose" title\x3d"Close" href\x3d"javascript:;"\x3e\x3c/a\x3e\x3c/li\x3e\x3c/ul\x3e\x3c/div\x3e'},
list:null,buttons:null,beforeLoad:function(c,a){c.skipSingle&&2>a.group.length?(a.helpers.buttons=!1,a.closeBtn=!0):a.margin["bottom"===c.position?2:0]+=30},onPlayStart:function(){this.buttons&&this.buttons.play.attr("title","Pause slideshow").addClass("btnPlayOn")},onPlayEnd:function(){this.buttons&&this.buttons.play.attr("title","Start slideshow").removeClass("btnPlayOn")},afterShow:function(c,a){var b=this.buttons;b||(this.list=e(c.tpl).addClass(c.position).appendTo("body"),b={prev:this.list.find(".btnPrev").click(d.prev),
next:this.list.find(".btnNext").click(d.next),play:this.list.find(".btnPlay").click(d.play),toggle:this.list.find(".btnToggle").click(d.toggle),close:this.list.find(".btnClose").click(d.close)});0<a.index||a.loop?b.prev.removeClass("btnDisabled"):b.prev.addClass("btnDisabled");a.loop||a.index<a.group.length-1?(b.next.removeClass("btnDisabled"),b.play.removeClass("btnDisabled")):(b.next.addClass("btnDisabled"),b.play.addClass("btnDisabled"));this.buttons=b;this.onUpdate(c,a)},onUpdate:function(c,a){var b;
this.buttons&&(b=this.buttons.toggle.removeClass("btnDisabled btnToggleOn"),a.canShrink?b.addClass("btnToggleOn"):a.canExpand||b.addClass("btnDisabled"))},beforeClose:function(){this.list&&this.list.remove();this.buttons=this.list=null}}})(jQuery);
(function(d){d.fancybox.helpers.thumbs={defaults:{width:50,height:50,position:"bottom",source:function(b){var a;b.element&&(a=d(b.element).find("img").attr("src"));!a&&("image"===b.type&&b.href)&&(a=b.href);return a}},wrap:null,list:null,width:0,init:function(b,a){var l=this,c,f=b.width,g=b.height,m=b.source;c="";for(var e=0;e<a.group.length;e++)c+='\x3cli\x3e\x3ca style\x3d"width:'+f+"px;height:"+g+'px;" href\x3d"javascript:jQuery.fancybox.jumpto('+e+');"\x3e\x3c/a\x3e\x3c/li\x3e';this.wrap=d('\x3cdiv id\x3d"fancybox-thumbs"\x3e\x3c/div\x3e').addClass(b.position).appendTo("body");
this.list=d("\x3cul\x3e"+c+"\x3c/ul\x3e").appendTo(this.wrap);d.each(a.group,function(b){var c=m(a.group[b]);c&&d("\x3cimg /\x3e").load(function(){var a=this.width,c=this.height,h,k,e;l.list&&(a&&c)&&(h=a/f,k=c/g,e=l.list.children().eq(b).find("a"),1<=h&&1<=k&&(h>k?(a=Math.floor(a/k),c=g):(a=f,c=Math.floor(c/h))),d(this).css({width:a,height:c,top:Math.floor(g/2-c/2),left:Math.floor(f/2-a/2)}),e.width(f).height(g),d(this).hide().appendTo(e).fadeIn(300))}).attr("src",c)});this.width=this.list.children().eq(0).outerWidth(!0);
this.list.width(this.width*(a.group.length+1)).css("left",Math.floor(0.5*d(window).width()-(a.index*this.width+0.5*this.width)))},beforeLoad:function(b,a){2>a.group.length?a.helpers.thumbs=!1:a.margin["top"===b.position?0:2]+=b.height+15},afterShow:function(b,a){if(this.list)this.onUpdate(b,a);else this.init(b,a);this.list.children().removeClass("active").eq(a.index).addClass("active")},onUpdate:function(b,a){this.list&&this.list.stop(!0).animate({left:Math.floor(0.5*d(window).width()-(a.index*this.width+
0.5*this.width))},150)},beforeClose:function(){this.wrap&&this.wrap.remove();this.list=this.wrap=null;this.width=0}}})(jQuery);
(function(d){var k=function(a,c,b){b=b||"";"object"===d.type(b)&&(b=d.param(b,!0));d.each(c,function(b,c){a=a.replace("$"+b,c||"")});b.length&&(a+=(0<a.indexOf("?")?"\x26":"?")+b);return a};d.fancybox.helpers.media={defaults:{youtube:{matcher:/(youtube\.com|youtu\.be|youtube-nocookie\.com)\/(watch\?v=|v\/|u\/|embed\/?)?(videoseries\?list=(.*)|[\w-]{11}|\?listType=(.*)&list=(.*)).*/i,params:{autoplay:1,autohide:1,fs:1,rel:0,hd:1,wmode:"opaque",enablejsapi:1},type:"iframe",url:"//www.youtube.com/embed/$3"},
vimeo:{matcher:/(?:vimeo(?:pro)?.com)\/(?:[^\d]+)?(\d+)(?:.*)/,params:{autoplay:1,hd:1,show_title:1,show_byline:1,show_portrait:0,fullscreen:1},type:"iframe",url:"//player.vimeo.com/video/$1"},metacafe:{matcher:/metacafe.com\/(?:watch|fplayer)\/([\w\-]{1,10})/,params:{autoPlay:"yes"},type:"swf",url:function(a,c,b){b.swf.flashVars="playerVars\x3d"+d.param(c,!0);return"//www.metacafe.com/fplayer/"+a[1]+"/.swf"}},dailymotion:{matcher:/dailymotion.com\/video\/(.*)\/?(.*)/,params:{additionalInfos:0,autoStart:1},
type:"swf",url:"//www.dailymotion.com/swf/video/$1"},twitvid:{matcher:/twitvid\.com\/([a-zA-Z0-9_\-\?\=]+)/i,params:{autoplay:0},type:"iframe",url:"//www.twitvid.com/embed.php?guid\x3d$1"},twitpic:{matcher:/twitpic\.com\/(?!(?:place|photos|events)\/)([a-zA-Z0-9\?\=\-]+)/i,type:"image",url:"//twitpic.com/show/full/$1/"},instagram:{matcher:/(instagr\.am|instagram\.com)\/p\/([a-zA-Z0-9_\-]+)\/?/i,type:"image",url:"//$1/p/$2/media/?size\x3dl"},google_maps:{matcher:/maps\.google\.([a-z]{2,3}(\.[a-z]{2})?)\/(\?ll=|maps\?)(.*)/i,
type:"iframe",url:function(a){return"//maps.google."+a[1]+"/"+a[3]+""+a[4]+"\x26output\x3d"+(0<a[4].indexOf("layer\x3dc")?"svembed":"embed")}}},beforeLoad:function(a,c){var b=c.href||"",g=!1,f,e,h;for(f in a)if(a.hasOwnProperty(f)&&(e=a[f],h=b.match(e.matcher))){g=e.type;b=d.extend(!0,{},e.params,c[f]||(d.isPlainObject(a[f])?a[f].params:null));b="function"===d.type(e.url)?e.url.call(this,h,b,c):k(e.url,h,b);break}g&&(c.href=b,c.type=g,c.autoHeight=!1)}}})(jQuery);
(function(c){c.fn.unveil=function(l,d){function g(){h=e.filter(function(){var a=c(this);if(!a.is(":hidden")){var b=f.scrollTop(),e=b+f.height(),d=a.offset().top;return d+a.height()>=b-k&&d<=e+k}}).trigger("unveil");e=e.not(h)}var f=c(window),k=l||0,m=1<window.devicePixelRatio?"data-src-retina":"data-src",e=this,h;this.one("unveil",function(){var a=this.getAttribute(m),a=a||this.getAttribute("data-src"),b=c(this);a&&imagesBaseUrl!=a?(b.load(function(){if(!this.complete||!c.browser.msie&&!this.naturalWidth)this.src=
assetsBaseUrl+"/assets/images/no_img.jpg"}),b.error(function(){this.src=assetsBaseUrl+"/assets/images/no_img.jpg"}),b.attr("src",a)):b.attr("src",assetsBaseUrl+"/assets/images/no_img.jpg");"function"===typeof d&&d.call(this)});f.on("scroll.unveil resize.unveil lookup.unveil show.unveil",g);g();return this}})(window.jQuery||window.Zepto);
(function(){window.Utils=window.Utils||{};window.Utils.goBack=function(){document.referrer&&0<document.referrer.length?window.location=document.referrer:window.history?window.history.back():window.location=context;0<location.href.indexOf("fromCheckout")&&(window.location=publicUrl)};window.Utils.getParameterByName=function(b,c){c=c.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var e=RegExp("[\\?\x26]"+c+"\x3d([^\x26#]*)").exec(b);return null==e?"":decodeURIComponent(e[1].replace(/\+/g," "))};window.Utils.removeParameterByName=
function(b,c){var e=b.split("?")[0],d,f=[];d=-1!==b.indexOf("?")?b.split("?")[1]:"";if(""!==d){for(var f=d.split("\x26"),g=f.length-1;0<=g;g-=1)d=f[g].split("\x3d")[0],d===c&&f.splice(g,1);e=e+"?"+f.join("\x26")}return e};window.Utils.removeAccents=function(b){return b.replace(/[éèêë]/g,"e").replace(/[áàãâä]/g,"a").replace(/[íìîï]/g,"i").replace(/[óòõôö]/g,"o").replace(/œ/g,"oe").replace(/[úùûü]/g,"u").replace(/[ç]/g,"c").replace(/[ñ]/g,"n")};window.Utils.validaCNPJ=function(b){b=b.replace(/[^\d]+/g,
"");if(""==b||14!=b.length||"00000000000000"==b||"11111111111111"==b||"22222222222222"==b||"33333333333333"==b||"44444444444444"==b||"55555555555555"==b||"66666666666666"==b||"77777777777777"==b||"88888888888888"==b||"99999999999999"==b)return!1;for(var c=b.length-2,e=b.substring(0,c),d=b.substring(c),f=0,g=c-7,h=c;1<=h;h--)f+=e.charAt(c-h)*g--,2>g&&(g=9);if((2>f%11?0:11-f%11)!=d.charAt(0))return!1;c+=1;e=b.substring(0,c);f=0;g=c-7;for(h=c;1<=h;h--)f+=e.charAt(c-h)*g--,2>g&&(g=9);return(2>f%11?0:
11-f%11)!=d.charAt(1)?!1:!0};window.Utils.getCookie=function(b){b+="\x3d";for(var c=document.cookie.split(";"),e=0;e<c.length;e++){for(var d=c[e];" "==d.charAt(0);)d=d.substring(1);if(-1!=d.indexOf(b))return d.substring(b.length,d.length)}return""};window.Utils.setCookie=function(b,c,e){var d=new Date;d.setTime(0<e?d.getTime()+864E5*e:e);e="expires\x3d"+d.toUTCString();document.cookie=b+"\x3d"+c+"; "+e+"; domain\x3d.livrariacultura.com.br; path\x3d/"};window.Utils.setSessionCookie=function(b,c){document.cookie=
b+"\x3d"+c+"; domain\x3d.livrariacultura.com.br; path\x3d/"};window.Utils.deleteCookie=function(b){document.cookie=b+"\x3d; domain\x3d.livrariacultura.com.br; path\x3d/; expires\x3dThu, 01 Jan 1970 00:00:01 GMT;"}})();
function loadWishList(b,c,e){var d=$(b).find("[data-wishlist\x3d'true']");d.html("\x3cli\x3e\x3cimg style\x3d'display: block; margin: auto; padding: 10px 0;' src\x3d'"+assetsBaseUrl+"/assets/images/ajax-loader.gif'/\x3e\x3c/li\x3e");$.ajax({url:context+"/ajax/wishlist/wishlist.jsp?productid\x3d"+c+"\x26skuid\x3d"+e,type:"GET",cache:!1,success:function(b,c,e){d.html(b)}})}
function updateTopWishList(){$.ajax({url:context+"/ajax/wishlist/top_nav_dropdown.jsp",type:"GET",cache:!1,success:function(b,c,e){$("#top-nav-dropdown").html(b)}})}function updateSideWishList(){$.ajax({url:context+"/ajax/wishlist/wishlists_list.jsp",type:"GET",cache:!1,success:function(b,c,e){$("#side-wishlist").html(b)}})}
function updateMyWishlist(){$.ajax({url:context+"/secure/ajax/wishlist/my_wishlists.jsp",type:"GET",cache:!1,success:function(b,c,e){$("#myLastGiftlists").html(b)}}).done(function(b){$("#myLastGiftlists").find("img[data-src]").unveil()})}function updateWishlistDivs(){updateTopWishList();$("#myLastGiftlists").length&&updateMyWishlist();$("#side-wishlist").length&&updateSideWishList()}
function createWishList(){form=$(".wishlist-create-list-form");$("#createGiftlist").hide();$(".sucesso").hide();$("#ajaxLoaderSmall").show();$.ajax({url:form.attr("action"),type:"POST",data:form.serialize(),success:function(b,c,e){$(".fancybox-inner").html(b);$("#wishlistName").val("");setTimeout(function(){updateWishlistDivs()},500)}})}
function subscribeNewsLetter(){form=$("#news-letter-subscription-form");$.ajax({url:form.attr("action"),type:"POST",data:form.serialize(),success:function(b,c,e){$.fancybox({minWidth:300,minHeight:100,enableEscapeButton:!1,overlayShow:!0,overlayOpacity:0,hideOnOverlayClick:!1,content:b});document.forms["news-letter-subscription-form"].reset()}})}
function deleteWishList(){form=$("#listFormDelete");$("#deleteGiftlist").hide();$(".sucesso").hide();$("#ajaxLoaderSmall").show();var b=$("#wishlists").val();$.ajax({url:form.attr("action"),type:"POST",data:form.serialize(),success:function(c,e,d){$(".fancybox-inner").html(c);$("#wishSideNav-"+b).hide();$("#wishPreviewNav-"+b).hide();$("#wishTopNav-"+b).hide();$("#wishMainNav-"+b).html("\x3cbr/\x3eEsta lista de desejos foi removida!");$("#wishlistCount").html($("#wishlistCount").html()-1);setTimeout(function(){updateWishlistDivs()},
500)}})}function removeGiftItem(b,c){$("#giftItemDelete"+c).hide();$("#giftItemLoader"+c).show();$.ajax({url:context+"/ajax/wishlist/delete_item_wishlist.jsp?gsId\x3d"+b+"\x26giId\x3d"+c,type:"GET",cache:!1,success:function(b,d,f){1==b?$("#giftItem"+c).slideUp("slow"):($("#giftItemLoader"+c).hide(),$("#giftItemDelete"+c).show())}})}function removeGiftItemDropdown(b,c){$.ajax({url:context+"/ajax/wishlist/delete_item_wishlist.jsp?gsId\x3d"+b+"\x26giId\x3d"+c,type:"GET",cache:!1})}
function addGiftItemDropdown(b,c,e){form=$("#wishlist-item-form-add"+b+c+e);$.ajax({url:form.attr("action"),type:"POST",data:form.serialize()})}
function openWishlistForm(b){$.fancybox.helpers.overlay.open({parent:$("body")});$.fancybox.showLoading();var c="";"delete"===b&&(c="_delete");wishlistUrl=isSecureConnection()?context+"/secure/ajax/wishlist/wishlist_form"+c+".jsp":context+"/ajax/wishlist/wishlist_form"+c+".jsp";$.ajax({url:wishlistUrl,type:"GET",cache:!1,success:function(b,c,f){$.fancybox.hideLoading();$.fancybox.helpers.overlay.close();$.fancybox({minWidth:300,minHeight:100,enableEscapeButton:!1,overlayShow:!0,overlayOpacity:0,hideOnOverlayClick:!1,
content:b})}})}function isSecureConnection(){var b=!1;"https:"===window.location.protocol&&(b=!0);return b}function scrollToElement(b){var c=void 0;(c=$(b))&&c.offset()&&$("html, body").animate({scrollTop:c.offset().top},1E3)}function loading(){$(".loading").css({height:$(document).height()+100,width:"100%"});$(".loading").show().fadeTo(0,0.7)}function loadingClose(){$(".loading").fadeOut(0,0.7)}"function"!=typeof String.prototype.replaceAll&&(String.prototype.replaceAll=function(b,c){return this.split(b).join(c)});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(b){return 0==this.indexOf(b)});$.fn.serializeObject=function(){var b={},c=this.serializeArray();$.each(c,function(){void 0!==b[this.name]?(b[this.name].push||(b[this.name]=[b[this.name]]),b[this.name].push(this.value||"")):b[this.name]=this.value||""});return b};
Number.prototype.format=function(b,c,e,d){c="\\d(?\x3d(\\d{"+(c||3)+"})+"+(0<b?"\\D":"$")+")";b=this.toFixed(Math.max(0,~~b));return(d?b.replace(".",d):b).replace(RegExp(c,"g"),"$\x26"+(e||","))};function monetaryFormat(b){b=parseFloat(b);return b.format(2,3,".",",")}
(function(b,c){SearchTracking=function(b){function c(){a=b(this);url=encodeURIComponent(a.data("href"));ref=encodeURIComponent(a.data("search-track-ref"));query=decodeURIComponent(a.data("ntt"));trackUrl=g+"/r/search/track?url\x3d"+url+"\x26query\x3d"+query+"\x26ref\x3d"+ref+"\x26_\x3d"+Math.random();a.attr("href",trackUrl)}var f={},g=void 0;f.init=function(f){g=f;b("[data-search-tracking\x3dtrue]").each(function(){b(this).on("mousedown",c)})};return f}(b);sysconf&&"true"==sysconf.searchTrackingEnabled&&
SearchTracking.init(c)})(jQuery,context);(function(){var b,c,e;b=$("#searchForm");c=$("#Ntt");e="";b.submit(function(b){e=c.val();1>$.trim(e).length&&b.preventDefault();c.val(e.toLowerCase())})})();
(function(){var b={running:!1};b.baseURL=context+"/busca";b.input=$("#Ntt");b.dimension=$("#N");b.results=$("#autocomplete-results");b.ajaxRequest=void 0;b.queueRequest=function(c){c.always(function(){b.ajaxRequest=void 0});b.ajaxRequest&&b.ajaxRequest.abort();b.ajaxRequest=c};b.results[0]||(b.results=b.input.parent().append('\x3cdiv id\x3d"autocomplete-results"\x3e\x3c/div\x3e'),b.results=$("#autocomplete-results"));b.input.blur(function(){setTimeout(function(){b.results.hide()},200)});b.delay=function(){var b=
0;return function(e,d){clearTimeout(b);b=setTimeout(e,d)}}();b.build=function(c){var e=b.input.val().toLowerCase(),d=c.autoSuggest,f="\x3cdiv\x3e\x3cul\x3e";for(i in c.categories)var g=c.categories[i],f=f+('\x3cli\x3e\x3ca href\x3d"'+b.baseURL+g.navigationState+'"\x3e\x3cb\x3e'+e+'\x3c/b\x3e em \x3ci class\x3d"icon c'+g.id+'"\x3e\x3c/i\x3e '+g.label+"\x3c/a\x3e\x3c/li\x3e");d&&(g=encodeURIComponent(d),g=g.replaceAll("%20","+"),f+='\x3cli style\x3d"background-color: #f2f2f2;"\x3e\x3ca href\x3d"'+b.baseURL+
"?Ntt\x3d"+g+'"\x3e\x3ci\x3eVocê quis dizer: '+d+" ?\x3c/i\x3e\x3c/a\x3e\x3c/li\x3e");if(c.dymterms)for(i in c.dymterms)d=c.dymterms[i],g=encodeURIComponent(d),g=g.replaceAll("%20","+"),f+='\x3cli style\x3d"background-color: #f2f2f2;"\x3e\x3ca href\x3d"'+b.baseURL+"?Ntt\x3d"+g+'"\x3e\x3ci\x3eVocê quis dizer: '+d+" ?\x3c/i\x3e\x3c/a\x3e\x3c/li\x3e";for(i in c.similarterms)g=c.similarterms[i],d=g.split("|")[0],g=g.split("|")[1],f+='\x3cli\x3e\x3ca href\x3d"'+b.baseURL+"?N\x3d"+d+'"\x3e'+g+"\x3c/a\x3e\x3c/li\x3e";
if(0<c.products.length){f+='\x3cdiv class\x3d"populares"\x3e\x3ch2\x3eProdutos Populares\x3c/h2\x3e\x3cul\x3e';for(i in c.products){d=c.products[i];if(!d.img||null==d.img)d.img=assetsBaseUrl+"/assets/images/no_img.jpg";"https:"==location.protocol&&(d.img=d.img.replace("http://statics.livrariacultura.net.br","https://statics.lcultura.secure.footprint.net"));f+='\x3cli\x3e\x3ca href\x3d"'+context+d.url+'" alt\x3d"'+d.displayName+'" title\x3d"'+d.displayName+'"\x3e\x3cdiv class\x3d"ribbons"\x3e\x3cb\x3e'+
d.type+" "+d.origin+'\x3c/b\x3e\x3c/div\x3e\x3cimg src\x3d"'+d.img+'" width\x3d"128" height\x3d"178" class\x3d"main-prod-img" onerror\x3d"this.src\x3dassetsBaseUrl+\'/assets/images/no_img.jpg\';"/\x3e\x3cdiv style\x3d"width: 128px; word-wrap: break-word;border-bottom: 0px;"\x3e\x3cp style\x3d"font-weight: 700;color: #0098aa;margin: 10px 0 10px;text-align: center;"\x3e'+d.displayName+"\x3c/p\x3e\x3c/div\x3e\x3c/a\x3e\x3c/li\x3e"}f+="\x3c/ul\x3e\x3c/div\x3e"}f+='\x3cdiv class\x3d"moar"\x3e\x3ca href\x3d"'+
b.baseURL+"?Ntt\x3d"+encodeURIComponent(e)+'" class\x3d"veja-mais"\x3eVer todos os resultados\x3c/a\x3e\x3c/div\x3e';b.results.html(f+"\x3c/ul\x3e\x3c/div\x3e");b.results.show()};b.autocomplete=function(){b.running=!0;try{var c=b.input.val(),e=b.dimension.val();if(3<$.trim(c).length){var d=$.get(context+"/r/search/autosuggest",{Nrpp:3,N:e,Ntt:c}).done(b.build);b.queueRequest(d)}else b.results.hide()}finally{b.running=!1}};sysconf&&"true"==sysconf.autoComplete&&b.input.keyup(function(){b.delay(b.autocomplete,
500)});b.input.focus(function(){sysconf&&"true"==sysconf.autoComplete&&b.autocomplete()})})();
(function(){function b(b,c){$("[data-buy-together\x3d"+b+"]").each(function(){c!=this.checked&&(this.checked=c)})}var c=$('\x3cimg class\x3d"loading-refinement" src\x3d"'+assetsBaseUrl+'/assets/images/custom/ajax-loader-small.gif"/\x3e'),e=window.BuyTogether||{};e.buy=function(){};e.clean=function(b){$.ajax({url:context+"/r/products/buytogether",type:"DELETE"}).success(b)};e.reloadBuyTogetherSummary=function(){$("[data-buy-together-summary]").load(context+"/ajax/buytogether/buytogether.jsp")};e.reloadBuyTogetherSelected=
function(){$.get(context+"/r/products/buytogether",function(b){$("[data-buy-together]").attr("checked",!1);b.forEach(function(b){$("[data-buy-together\x3d"+b+"]").each(function(){this.checked=!0})})})};$("[data-buy-together]").on("change",function(){var d=$(this),f=$(this).data("buy-together"),g=this.checked,h=g?"PUT":"DELETE";d.hide();d.parent().prepend(c);$.ajax({url:context+"/r/products/buytogether/"+f,type:h}).always(function(){try{e.reloadBuyTogetherSummary(),b(f,g)}finally{d.parent().find(c).remove(),
d.show()}})});0<$("[data-buy-together]").length&&(e.reloadBuyTogetherSummary(),e.reloadBuyTogetherSelected());window.BuyTogether=e})();
$(document).ready(function(){function b(){$("[data-subcategory]").each(function(){var b=$(this).data("subcategory"),c=$(this).data("subcategoryname"),d=$(this).closest(".refinement-container");$.get(context+"/ajax/categories/query"+b+"\x26currentUrl\x3d"+window.location.pathname+"\x26hideFeatureds\x3dtrue",function(b){b=$(b);b.find(".cat-title").html(c+" por gênero");d.after(b)})})}function c(){$(".toggle-refinement").click(function(d){if(!$(this).data("loading")){var e=$(this).data("href"),h=$(this).closest("[data-content-collection]").data("content-collection");
h&&0<h.length&&($(this).append('\x3cimg class\x3d"loading-refinement" src\x3d"'+assetsBaseUrl+'/assets/images/custom/ajax-loader-small.gif"/\x3e'),$(this).attr("data-loading","true"),$("#dimensions-container").load(context+"/ajax/assembler.jsp"+e+"\x26contentCollection\x3d"+h+"\x26currentUrl\x3d"+window.location.pathname+" #dimensions-container",function(){b();c()}))}d.preventDefault()})}$("img[data-src]").unveil();$("#categories .category .cat-title").unbind("click").click(function(){$(this).parent().find(".cat-links").eq(0).slideToggle("fast",
function(){$(this).parent().toggleClass("closed")})});b();c();$("[data-parent-form-submit\x3d'true']").click(function(b){b.preventDefault();(form=$(this).closest("form"))&&form.submit()});$(".collaborator-bxslider").bxSlider({pager:!1});$('.conteudo-Cultura-curso input[type\x3d"submit"]').click(function(){$(".conteudo-Cultura-curso .error").remove();!1==$('.conteudo-Cultura-curso input[type\x3d"checkbox"]').prop("checked")?$('.conteudo-Cultura-curso input[type\x3d"checkbox"] + p').after('\x3cp class\x3d"error"\x3ePara continuar você precisa aceitar os termos.\x3c/p\x3e'):
$("#addCourseToCart").submit()});menuColors={livros:"purple",ebooks:"orange","cultura em curso":"green",kobo:"blue",games:"orange","papelaria \x26 etc":"pink",filmes:"pink","música":"green",brinquedos:"blue",geek:"blue"};var e=["purple","orange","blue","pink","green"],d=0;$(".search-N a, #clbutton").each(function(){value=$(this).text().trim().toLowerCase();color=menuColors[value];void 0!=color?$(this).attr("data-class",color):"todo o site"==value?$(this).attr("data-class","custom-btn-search"):(colorIdx=
d%5,d++,$(this).attr("data-class",e[colorIdx]))});searchBtClass=$("#clbutton").attr("data-class");$("#clbutton").removeClass("custom-btn-search").addClass(searchBtClass)});$(window).load(function(){$("[img-on-error]").each(function(){if(!this.complete||!$.browser.msie&&!this.naturalWidth)this.src=assetsBaseUrl+"/assets/images/no_img.jpg",this.removeAttribute("img-on-error")})});
function generateCookies(a){function c(a){(void 0!==b||void 0!==d)&&Utils.deleteCookie(a)}var b=a.id_link,d=a.zanpid;a="lomadee_traffic";-1<["12571","8104"].indexOf(b)?Utils.setCookie(a,b,30):c(a);a="afilio";-1<["12694"].indexOf(b)?Utils.setCookie(a,b,30):c(a);a="zanpid";void 0!==d?Utils.setSessionCookie(a,d):c(a)};
